name: Deploy Multiple Images to Docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t andyfeetenby/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true andyfeetenby/react-test npm test

      - run: docker build -r andyfeetenby/multi-client ./client
      - run: docker build -r andyfeetenby/multi-nginx ./nginx
      - run: docker build -r andyfeetenby/multi-server ./server
      - run: docker build -r andyfeetenby/multi-worker ./worker

      
      - run: docker push andyfeetenby/multi-client 
      - run: docker push andyfeetenby/multi-nginx 
      - run: docker push andyfeetenby/multi-server 
      - run: docker push andyfeetenby/multi-worker 